name: C_C++_CI

on:
  pull_request:
    branches:
      - master

jobs:
  bash-example:
    runs-on: ubuntu-latest
    steps:
      - name: Group of log lines
        run: |
            echo "::group::My title"
            echo "Inside group"
            echo "::endgroup::"
  build-with-gcc:
    uses: NWChemEx-Project/.github/.github/workflows/c-cpp_tmpl.yaml@cache-build2
    with: 
      cached-libs: 'tiledarray'
      dependencies: 'ninja gcc gcovr openblas cblas lapacke scalapack boost eigen3 openmpi'
      clang-build: false
      gcc-build: true
      ninja_build: true
    secrets:
      CPP_GITHUB_TOKEN: ${{ secrets.CPP_GITHUB_TOKEN }}
  bash-example-2:
    runs-on: ubuntu-latest
    steps:
      - name: Group of log lines
        run: |
            echo "::group::My title"
            echo "Inside group"
            echo "::endgroup::"
