name: Build and Deploy Documentation
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  Build-Documentation:
    uses: NWChemEx-Project/.github/.github/workflows/deploy_docs_tmpl.yaml@master
    with: 
      target: tensorwrapper_cxx_api
      dependencies: cmake doxygen sphinx
