name: Build and Deploy Documentation
on:
  push:
    branches:
      - master

jobs:
  Build-Documentation:
    uses: NWChemEx-Project/.github/.github/workflows/deploy_docs_tmpl.yaml@cache-build2
    with: 
      target: tensorwrapper_cxx_api
      dependencies: cmake doxygen sphinx
