name: Test Documentation
on:
  pull_request:
    branches:
      - master

jobs:
  Build-Documentation:
    uses: NWChemEx-Project/.github/.github/workflows/test_docs_tmpl.yaml@master
    with:
      target: tensorwrapper_cxx_api
      dependencies: cmake doxygen sphinx
